### ISSUE TITLE
Question 29 (line 536): correct answer null

### ISSUE THREAD

**Issue by viettham1998** [tmkhiem/thi-vien-chuc#2]
Chưa chọn đáp án câu này

**Comment by tmkhiem** [comment]
Câu nào đúng ta :v ?

**Comment by viettham1998** [comment]
![Screenshot from 2024-05-22 15-45-25](https://github.com/tmkhiem/thi-vien-chuc/assets/44217470/b8bad8dc-fccb-424b-a6b1-d05ff2363796)
:D

**Comment by viettham1998** [comment]
![Screenshot from 2024-05-22 15-52-37](https://github.com/tmkhiem/thi-vien-chuc/assets/44217470/ff1545fa-b83f-4919-a9f6-89ff6bd4dfcd)
Thấy nó có cả 4 đáp án: https://luathoanganh.vn/giao-duc/nhiem-vu-va-quyen-han-cua-co-so-giao-duc-dai-hoc-trong-hoat-dong-khoa-hoc-va-cong-nghe-la-gi-lha10088.html
